name: Python application

on: [pull_request]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      working-directory: ./exemplo
      run: |

        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync -d
    - name: Lint with flake8
      working-directory: ./exemplo
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 .. --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 .. --count --exit-zero --max-complexity=10 --statistics
    - name: Test with pytest
      working-directory: ./exemplo
      run: |
        cp ../contrib/env-amostra .env
        pipenv run pytest --cov=../django_pagarme
    - name: Posting Coverage
      working-directory: ./exemplo
      env:
        CODECOV_TOKEN: "2e4566cb-8fbb-42d9-bc91-d2b1b4719932"
      run: |
        pipenv run codecov

